#cache:
#  directories:
#    - $HOME/.m2
language: java
jdk:
  - oraclejdk8
env:
  - ACTIVE_ENV=travis
install: true
script:
  - mvn clean install -Denvironments=travis -Dversion=1.0.$TRAVIS_BUILD_NUMBER